import re

from split.services.receipt_parser.utils import detect_as_word

DENIED_WORDS_LIST = [
    "balance",
    "boleta",
    "cliente",
    "consumo",
    "convenios",
    "credito",
    "debito",
    "descuento",
    "dscto",
    "fecha",
    "iva",
    "local",
    "monto",
    "neto",
    "pago",
    "propina",
    "sugerida",
    "tarjeta",
    "tienda",
    "total",
    "vuelto",
]

DENIED_WORDS_EXPRESSION = re.compile(
    detect_as_word("|".join(DENIED_WORDS_LIST)), re.IGNORECASE
)

DESCRIPTION_EXPRESSION_FRAGMENT = (
    r"(?P<description>\d* ?[a-zA-Z\(\)][a-zA-Z0-9 \(\)]+[a-zA-Z\(\)])"
)
DESCRIPTION_WITH_FINAL_NUMBERS_EXPRESSION_FRAGMENT = (
    r"(?P<description>\d* ?[a-zA-Z\(\)][a-zA-Z0-9 \(\)]+?)"
)
AMOUNT_EXPRESSION_FRAGMENT = r"(?P<amount>[0-9]{1,2})"
FULL_PRICE_EXPRESSION_FRAGMENT = (
    r"((?P<price_1>[0-9]{3,6})(\s+(?P<price_2>[0-9]{3,6}))?)"
)
SEPARATOR = r"\s+"


def generate_expression(*fragments: str) -> re.Pattern:
    return re.compile(f"^{SEPARATOR.join(fragments)}$")


AMOUNT_DESCRIPTION_PRICE_EXPRESSION = generate_expression(
    AMOUNT_EXPRESSION_FRAGMENT,
    DESCRIPTION_EXPRESSION_FRAGMENT,
    FULL_PRICE_EXPRESSION_FRAGMENT,
)

DESCRIPTION_AMOUNT_PRICE_EXPRESSION = generate_expression(
    DESCRIPTION_EXPRESSION_FRAGMENT,
    AMOUNT_EXPRESSION_FRAGMENT,
    FULL_PRICE_EXPRESSION_FRAGMENT,
)

DESCRIPTION_PRICE_AMOUNT_EXPRESSION = generate_expression(
    DESCRIPTION_EXPRESSION_FRAGMENT,
    FULL_PRICE_EXPRESSION_FRAGMENT,
    AMOUNT_EXPRESSION_FRAGMENT,
)

AMOUNT_PRICE_DESCRIPTION_EXPRESSION = generate_expression(
    AMOUNT_EXPRESSION_FRAGMENT,
    FULL_PRICE_EXPRESSION_FRAGMENT,
    DESCRIPTION_EXPRESSION_FRAGMENT,
)

PRICE_DESCRIPTION_AMOUNT_EXPRESSION = generate_expression(
    FULL_PRICE_EXPRESSION_FRAGMENT,
    DESCRIPTION_EXPRESSION_FRAGMENT,
    AMOUNT_EXPRESSION_FRAGMENT,
)

PRICE_AMOUNT_DESCRIPTION_EXPRESSION = generate_expression(
    FULL_PRICE_EXPRESSION_FRAGMENT,
    AMOUNT_EXPRESSION_FRAGMENT,
    DESCRIPTION_EXPRESSION_FRAGMENT,
)

DESCRIPTION_PRICE_EXPRESSION = generate_expression(
    DESCRIPTION_EXPRESSION_FRAGMENT,
    FULL_PRICE_EXPRESSION_FRAGMENT,
)

PRICE_DESCRIPTION_EXPRESSION = generate_expression(
    FULL_PRICE_EXPRESSION_FRAGMENT,
    DESCRIPTION_EXPRESSION_FRAGMENT,
)

AMOUNT_DESCRIPTION_WITH_FINAL_NUMBERS_PRICE_EXPRESSION = generate_expression(
    AMOUNT_EXPRESSION_FRAGMENT,
    DESCRIPTION_WITH_FINAL_NUMBERS_EXPRESSION_FRAGMENT,
    FULL_PRICE_EXPRESSION_FRAGMENT,
)

DESCRIPTION_WITH_FINAL_NUMBERS_AMOUNT_PRICE_EXPRESSION = generate_expression(
    DESCRIPTION_WITH_FINAL_NUMBERS_EXPRESSION_FRAGMENT,
    AMOUNT_EXPRESSION_FRAGMENT,
    FULL_PRICE_EXPRESSION_FRAGMENT,
)

DESCRIPTION_WITH_FINAL_NUMBERS_PRICE_AMOUNT_EXPRESSION = generate_expression(
    DESCRIPTION_WITH_FINAL_NUMBERS_EXPRESSION_FRAGMENT,
    FULL_PRICE_EXPRESSION_FRAGMENT,
    AMOUNT_EXPRESSION_FRAGMENT,
)

AMOUNT_PRICE_DESCRIPTION_WITH_FINAL_NUMBERS_EXPRESSION = generate_expression(
    AMOUNT_EXPRESSION_FRAGMENT,
    FULL_PRICE_EXPRESSION_FRAGMENT,
    DESCRIPTION_WITH_FINAL_NUMBERS_EXPRESSION_FRAGMENT,
)

PRICE_DESCRIPTION_WITH_FINAL_NUMBERS_AMOUNT_EXPRESSION = generate_expression(
    FULL_PRICE_EXPRESSION_FRAGMENT,
    DESCRIPTION_WITH_FINAL_NUMBERS_EXPRESSION_FRAGMENT,
    AMOUNT_EXPRESSION_FRAGMENT,
)

PRICE_AMOUNT_DESCRIPTION_WITH_FINAL_NUMBERS_EXPRESSION = generate_expression(
    FULL_PRICE_EXPRESSION_FRAGMENT,
    AMOUNT_EXPRESSION_FRAGMENT,
    DESCRIPTION_WITH_FINAL_NUMBERS_EXPRESSION_FRAGMENT,
)

DESCRIPTION_WITH_FINAL_NUMBERS_PRICE_EXPRESSION = generate_expression(
    DESCRIPTION_WITH_FINAL_NUMBERS_EXPRESSION_FRAGMENT,
    FULL_PRICE_EXPRESSION_FRAGMENT,
)

PRICE_DESCRIPTION_WITH_FINAL_NUMBERS_EXPRESSION = generate_expression(
    FULL_PRICE_EXPRESSION_FRAGMENT,
    DESCRIPTION_WITH_FINAL_NUMBERS_EXPRESSION_FRAGMENT,
)


def search(string: str) -> dict[str, str | int] | None:
    if DENIED_WORDS_EXPRESSION.search(string):
        return None
    expressions = [
        AMOUNT_DESCRIPTION_PRICE_EXPRESSION,
        AMOUNT_DESCRIPTION_WITH_FINAL_NUMBERS_PRICE_EXPRESSION,
        DESCRIPTION_AMOUNT_PRICE_EXPRESSION,
        DESCRIPTION_WITH_FINAL_NUMBERS_AMOUNT_PRICE_EXPRESSION,
        DESCRIPTION_PRICE_AMOUNT_EXPRESSION,
        DESCRIPTION_WITH_FINAL_NUMBERS_PRICE_AMOUNT_EXPRESSION,
        AMOUNT_PRICE_DESCRIPTION_EXPRESSION,
        AMOUNT_PRICE_DESCRIPTION_WITH_FINAL_NUMBERS_EXPRESSION,
        PRICE_DESCRIPTION_AMOUNT_EXPRESSION,
        PRICE_DESCRIPTION_WITH_FINAL_NUMBERS_AMOUNT_EXPRESSION,
        PRICE_AMOUNT_DESCRIPTION_EXPRESSION,
        PRICE_AMOUNT_DESCRIPTION_WITH_FINAL_NUMBERS_EXPRESSION,
        DESCRIPTION_PRICE_EXPRESSION,
        DESCRIPTION_WITH_FINAL_NUMBERS_PRICE_EXPRESSION,
        PRICE_DESCRIPTION_EXPRESSION,
        PRICE_DESCRIPTION_WITH_FINAL_NUMBERS_EXPRESSION,
    ]
    for expression in expressions:
        search_result = expression.search(string)
        if search_result is not None:
            raw_result = search_result.groupdict()
            price_1 = int(raw_result["price_1"])
            price_2 = int(raw_result["price_2"] or "0")
            full_price = max(price_1, price_2)
            if full_price < 100:
                return None
            final_result: dict[str, str | int] = {
                "description": raw_result["description"],
                "full_price": full_price,
            }
            amount = raw_result.get("amount")
            if amount:
                final_result = {**final_result, "amount": int(amount)}
            return final_result
    return None
