version: '3.9'
services:
  db:
    image: postgres:14.2
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust  # Insecure connection, only for local
    networks:
      - backend
  web:
    init: true
    build: .
    command: uvicorn split.main:app --host 0.0.0.0 --reload
    environment:
      DATABASE_URL: postgresql://postgres@db:5432/postgres
      ALLOWED_ORIGINS: http://localhost:3000 http://localhost:5173 http://localhost:5174
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - backend

volumes:
  database:

networks:
  backend:
